### ISSUE TITLE
Where twitter?

### ISSUE THREAD

**Issue by MaxAve** [blurrycmd/SpendElonsMoney#1]
Make it so you can buy twitter pls (bonus points if the logo turns into the current one once you do)

**Comment by ItsCR24** [comment]
Soon™
![smart_tortol](https://github.com/user-attachments/assets/f9991d00-078e-4f69-b2a3-e1f944326811)
(This me is me, if you even care. Don't judge my code)

**Comment by ItsCR24** [comment]
Soon™
![smart_tortol](https://github.com/user-attachments/assets/8a8bc3a5-b9df-4276-ad8d-df07aed48523)
(This is me, if you even care. Don't judge my code.)
